const tools = [
  {name:'BloxMake Previewer',description:'Preview Roblox assets and library items before using them in your project.',category:'Assets',icon:'◈',color:'blue',url:'https://bloxmake.com/library/previewer'},
  {name:'Roblox Studio',description:'The official all-in-one environment for building, scripting, and testing experiences.',category:'Create',icon:'▣',color:'purple',url:'https://create.roblox.com/'},
  {name:'Luau Playground',description:'Write and test Luau code in your browser with instant feedback.',category:'Code',icon:'⌘',color:'green',url:'https://luau.org/demo'},
  {name:'Roblox API Reference',description:'Search classes, properties, events, and services from the Roblox engine.',category:'Code',icon:'{}',color:'blue',url:'https://create.roblox.com/docs/reference/engine'},
  {name:'Creator Store',description:'Find models, plugins, audio, fonts, and other assets for your experiences.',category:'Assets',icon:'◇',color:'orange',url:'https://create.roblox.com/marketplace'},
  {name:'Developer Hub',description:'Official guides and tutorials for every part of Roblox development.',category:'Learn',icon:'✦',color:'purple',url:'https://create.roblox.com/docs'},
  {name:'DevForum',description:'Connect with other creators, get help, and follow platform updates.',category:'Learn',icon:'◉',color:'green',url:'https://devforum.roblox.com/'},
  {name:'Asset Delivery API',description:'Explore asset metadata and delivery endpoints in the official docs.',category:'Code',icon:'↯',color:'orange',url:'https://create.roblox.com/docs/reference/cloud/assets'},
  {name:'Animation Editor',description:'Create and edit custom animations directly inside Roblox Studio.',category:'Create',icon:'⌁',color:'blue',url:'https://create.roblox.com/docs/art/animation/editor'}
];
const grid=document.querySelector('#tool-grid'), search=document.querySelector('#search'), count=document.querySelector('#tool-count'), empty=document.querySelector('#empty');
let category='All', favoritesOnly=false, favorites=JSON.parse(localStorage.getItem('roblox-toolkit-favorites')||'[]');
function render(){const query=search.value.toLowerCase().trim();const shown=tools.filter(t=>(category==='All'||t.category===category)&&(!favoritesOnly||favorites.includes(t.name))&&(`${t.name} ${t.description} ${t.category}`.toLowerCase().includes(query)));count.textContent=`${shown.length} tool${shown.length===1?'':'s'} available`;empty.hidden=shown.length>0;grid.innerHTML=shown.map(t=>`<article class="tool-card"><button class="heart ${favorites.includes(t.name)?'saved':''}" aria-label="${favorites.includes(t.name)?'Remove from':'Add to'} favorites" data-favorite="${t.name}">${favorites.includes(t.name)?'♥':'♡'}</button><div class="tool-icon ${t.color}">${t.icon}</div><h3>${t.name}</h3><p>${t.description}</p><div class="tool-meta"><span class="tag">${t.category}</span><a class="open" href="${t.url}" target="_blank" rel="noreferrer">Open ↗</a></div></article>`).join('');document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>{const n=b.dataset.favorite;favorites=favorites.includes(n)?favorites.filter(x=>x!==n):[...favorites,n];localStorage.setItem('roblox-toolkit-favorites',JSON.stringify(favorites));render()})}
document.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');button.classList.add('active');category=button.dataset.filter;render()});search.oninput=render;document.querySelector('#favorites-toggle').onclick=e=>{favoritesOnly=!favoritesOnly;e.currentTarget.classList.toggle('active',favoritesOnly);render()};render();
